# Generated by Django 6.0.4 on 2026-04-26 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insulin_type', models.CharField(choices=[('RAPID_ACTING', 'Rapid-acting insulin (bolus)'), ('LONG_ACTING', 'Long-acting insulin (basal)')], max_length=30)),
                ('dose_units', models.PositiveIntegerField()),
                ('injected_at', models.DateTimeField()),
                ('recorded_by_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('duplicate_risk_flag', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injection_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-injected_at'],
            },
        ),
        migrations.CreateModel(
            name='MealReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_at', models.DateTimeField()),
                ('offset_minutes', models.PositiveIntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('injection_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_reminders', to='injections.injectionlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['remind_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_reminder_enabled', models.BooleanField(default=False)),
                ('meal_reminder_offset_minutes', models.PositiveIntegerField(default=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
